services:
  simple-db:
    image: postgres
    environment:
      POSTGRES_USER: ${db_user}
      POSTGRES_PASSWORD: ${db_password}
      POSTGRES_DB: ${db_name}
    ports:
      - "9001:5432"
    networks:
      - simple-network
  simple-java-rest-backend:
    image: "simple-java-rest-backend:${version}"
    environment:
      - db_password
      - db_user
      - db_name
      - db_endpoint
    ports:
      - "8080:8080"
      - "4848:4848"
    depends_on:
      - simple-db
    networks:
      - simple-network
networks:
  simple-network:
