services:
  simple-db:
    image: postgres
    environment:
      POSTGRES_USER: simple-db
      POSTGRES_PASSWORD: simple-db
      POSTGRES_DB: simple-db
    ports:
      - "9001:5432"
    networks:
      - simple-network
  simple-java-rest-backend:
    image: com.mdevoc/simple-java-rest-backend:${BACKEND_VERSION}
    ports:
      - "8080:8080"
      - "4848:4848"
    depends_on:
      - simple-db
    networks:
      - simple-network
networks:
  simple-network:
